
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("469c3cae-1c4b-42ee-91f3-5fa7f8d12b3f")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("SI_DBModel", "FK_BillInfo_Customer", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Customer), "BillInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(BillInfo), True)>
<Assembly: EdmRelationshipAttribute("SI_DBModel", "FK_OrderInfo_Customer", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Customer), "OrderInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(OrderInfo), True)>
<Assembly: EdmRelationshipAttribute("SI_DBModel", "FK_Stock_Product", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Product), "Stock", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Stock), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class SI_DBEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new SI_DBEntities object using the connection string found in the 'SI_DBEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=SI_DBEntities", "SI_DBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new SI_DBEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "SI_DBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new SI_DBEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "SI_DBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property BillInfoes() As ObjectSet(Of BillInfo)
        Get
            If (_BillInfoes Is Nothing) Then
                _BillInfoes = MyBase.CreateObjectSet(Of BillInfo)("BillInfoes")
            End If
            Return _BillInfoes
        End Get
    End Property

    Private _BillInfoes As ObjectSet(Of BillInfo)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Customers() As ObjectSet(Of Customer)
        Get
            If (_Customers Is Nothing) Then
                _Customers = MyBase.CreateObjectSet(Of Customer)("Customers")
            End If
            Return _Customers
        End Get
    End Property

    Private _Customers As ObjectSet(Of Customer)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property InventoryCategories() As ObjectSet(Of InventoryCategory)
        Get
            If (_InventoryCategories Is Nothing) Then
                _InventoryCategories = MyBase.CreateObjectSet(Of InventoryCategory)("InventoryCategories")
            End If
            Return _InventoryCategories
        End Get
    End Property

    Private _InventoryCategories As ObjectSet(Of InventoryCategory)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property OrderInfoes() As ObjectSet(Of OrderInfo)
        Get
            If (_OrderInfoes Is Nothing) Then
                _OrderInfoes = MyBase.CreateObjectSet(Of OrderInfo)("OrderInfoes")
            End If
            Return _OrderInfoes
        End Get
    End Property

    Private _OrderInfoes As ObjectSet(Of OrderInfo)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Products() As ObjectSet(Of Product)
        Get
            If (_Products Is Nothing) Then
                _Products = MyBase.CreateObjectSet(Of Product)("Products")
            End If
            Return _Products
        End Get
    End Property

    Private _Products As ObjectSet(Of Product)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Registrations() As ObjectSet(Of Registration)
        Get
            If (_Registrations Is Nothing) Then
                _Registrations = MyBase.CreateObjectSet(Of Registration)("Registrations")
            End If
            Return _Registrations
        End Get
    End Property

    Private _Registrations As ObjectSet(Of Registration)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Stocks() As ObjectSet(Of Stock)
        Get
            If (_Stocks Is Nothing) Then
                _Stocks = MyBase.CreateObjectSet(Of Stock)("Stocks")
            End If
            Return _Stocks
        End Get
    End Property

    Private _Stocks As ObjectSet(Of Stock)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property sysdiagrams() As ObjectSet(Of sysdiagram)
        Get
            If (_sysdiagrams Is Nothing) Then
                _sysdiagrams = MyBase.CreateObjectSet(Of sysdiagram)("sysdiagrams")
            End If
            Return _sysdiagrams
        End Get
    End Property

    Private _sysdiagrams As ObjectSet(Of sysdiagram)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Users() As ObjectSet(Of User)
        Get
            If (_Users Is Nothing) Then
                _Users = MyBase.CreateObjectSet(Of User)("Users")
            End If
            Return _Users
        End Get
    End Property

    Private _Users As ObjectSet(Of User)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Vendors() As ObjectSet(Of Vendor)
        Get
            If (_Vendors Is Nothing) Then
                _Vendors = MyBase.CreateObjectSet(Of Vendor)("Vendors")
            End If
            Return _Vendors
        End Get
    End Property

    Private _Vendors As ObjectSet(Of Vendor)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the BillInfoes EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToBillInfoes(ByVal billInfo As BillInfo)
        MyBase.AddObject("BillInfoes", billInfo)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCustomers(ByVal customer As Customer)
        MyBase.AddObject("Customers", customer)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the InventoryCategories EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToInventoryCategories(ByVal inventoryCategory As InventoryCategory)
        MyBase.AddObject("InventoryCategories", inventoryCategory)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the OrderInfoes EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToOrderInfoes(ByVal orderInfo As OrderInfo)
        MyBase.AddObject("OrderInfoes", orderInfo)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToProducts(ByVal product As Product)
        MyBase.AddObject("Products", product)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Registrations EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToRegistrations(ByVal registration As Registration)
        MyBase.AddObject("Registrations", registration)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Stocks EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToStocks(ByVal stock As Stock)
        MyBase.AddObject("Stocks", stock)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTosysdiagrams(ByVal sysdiagram As sysdiagram)
        MyBase.AddObject("sysdiagrams", sysdiagram)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToUsers(ByVal user As User)
        MyBase.AddObject("Users", user)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Vendors EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToVendors(ByVal vendor As Vendor)
        MyBase.AddObject("Vendors", vendor)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SI_DBModel", Name:="BillInfo")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class BillInfo
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new BillInfo object.
    ''' </summary>
    ''' <param name="invoiceNo">Initial value of the InvoiceNo property.</param>
    Public Shared Function CreateBillInfo(invoiceNo As Global.System.String) As BillInfo
        Dim billInfo as BillInfo = New BillInfo
        billInfo.InvoiceNo = invoiceNo
        Return billInfo
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property InvoiceNo() As Global.System.String
        Get
            Return _InvoiceNo
        End Get
        Set
            If (_InvoiceNo <> Value) Then
                OnInvoiceNoChanging(value)
                ReportPropertyChanging("InvoiceNo")
                _InvoiceNo = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("InvoiceNo")
                OnInvoiceNoChanged()
            End If
        End Set
    End Property

    Private _InvoiceNo As Global.System.String
    Private Partial Sub OnInvoiceNoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnInvoiceNoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property BillingDate() As Global.System.String
        Get
            Return _BillingDate
        End Get
        Set
            OnBillingDateChanging(value)
            ReportPropertyChanging("BillingDate")
            _BillingDate = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("BillingDate")
            OnBillingDateChanged()
        End Set
    End Property

    Private _BillingDate As Global.System.String
    Private Partial Sub OnBillingDateChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBillingDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CustomerNo() As Global.System.String
        Get
            Return _CustomerNo
        End Get
        Set
            OnCustomerNoChanging(value)
            ReportPropertyChanging("CustomerNo")
            _CustomerNo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CustomerNo")
            OnCustomerNoChanged()
        End Set
    End Property

    Private _CustomerNo As Global.System.String
    Private Partial Sub OnCustomerNoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCustomerNoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CustomerName() As Global.System.String
        Get
            Return _CustomerName
        End Get
        Set
            OnCustomerNameChanging(value)
            ReportPropertyChanging("CustomerName")
            _CustomerName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CustomerName")
            OnCustomerNameChanged()
        End Set
    End Property

    Private _CustomerName As Global.System.String
    Private Partial Sub OnCustomerNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCustomerNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property subTotal() As Nullable(Of Global.System.Int32)
        Get
            Return _subTotal
        End Get
        Set
            OnsubTotalChanging(value)
            ReportPropertyChanging("subTotal")
            _subTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("subTotal")
            OnsubTotalChanged()
        End Set
    End Property

    Private _subTotal As Nullable(Of Global.System.Int32)
    Private Partial Sub OnsubTotalChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnsubTotalChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TaxPercentage() As Nullable(Of Global.System.Double)
        Get
            Return _TaxPercentage
        End Get
        Set
            OnTaxPercentageChanging(value)
            ReportPropertyChanging("TaxPercentage")
            _TaxPercentage = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TaxPercentage")
            OnTaxPercentageChanged()
        End Set
    End Property

    Private _TaxPercentage As Nullable(Of Global.System.Double)
    Private Partial Sub OnTaxPercentageChanging(value As Nullable(Of Global.System.Double))
    End Sub

    Private Partial Sub OnTaxPercentageChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TaxAmount() As Nullable(Of Global.System.Int32)
        Get
            Return _TaxAmount
        End Get
        Set
            OnTaxAmountChanging(value)
            ReportPropertyChanging("TaxAmount")
            _TaxAmount = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TaxAmount")
            OnTaxAmountChanged()
        End Set
    End Property

    Private _TaxAmount As Nullable(Of Global.System.Int32)
    Private Partial Sub OnTaxAmountChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnTaxAmountChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property GrandTotal() As Nullable(Of Global.System.Int32)
        Get
            Return _GrandTotal
        End Get
        Set
            OnGrandTotalChanging(value)
            ReportPropertyChanging("GrandTotal")
            _GrandTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("GrandTotal")
            OnGrandTotalChanged()
        End Set
    End Property

    Private _GrandTotal As Nullable(Of Global.System.Int32)
    Private Partial Sub OnGrandTotalChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnGrandTotalChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TotalPayment() As Nullable(Of Global.System.Int32)
        Get
            Return _TotalPayment
        End Get
        Set
            OnTotalPaymentChanging(value)
            ReportPropertyChanging("TotalPayment")
            _TotalPayment = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TotalPayment")
            OnTotalPaymentChanged()
        End Set
    End Property

    Private _TotalPayment As Nullable(Of Global.System.Int32)
    Private Partial Sub OnTotalPaymentChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnTotalPaymentChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PaymentDue() As Nullable(Of Global.System.Int32)
        Get
            Return _PaymentDue
        End Get
        Set
            OnPaymentDueChanging(value)
            ReportPropertyChanging("PaymentDue")
            _PaymentDue = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PaymentDue")
            OnPaymentDueChanged()
        End Set
    End Property

    Private _PaymentDue As Nullable(Of Global.System.Int32)
    Private Partial Sub OnPaymentDueChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnPaymentDueChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SI_DBModel", "FK_BillInfo_Customer", "Customer")>
    Public Property Customer() As Customer
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("SI_DBModel.FK_BillInfo_Customer", "Customer").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("SI_DBModel.FK_BillInfo_Customer", "Customer").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CustomerReference() As EntityReference(Of Customer)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("SI_DBModel.FK_BillInfo_Customer", "Customer")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Customer)("SI_DBModel.FK_BillInfo_Customer", "Customer", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SI_DBModel", Name:="Customer")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Customer
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Customer object.
    ''' </summary>
    ''' <param name="customerNo">Initial value of the CustomerNo property.</param>
    Public Shared Function CreateCustomer(customerNo As Global.System.String) As Customer
        Dim customer as Customer = New Customer
        customer.CustomerNo = customerNo
        Return customer
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property B_Name() As Global.System.String
        Get
            Return _B_Name
        End Get
        Set
            OnB_NameChanging(value)
            ReportPropertyChanging("B_Name")
            _B_Name = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("B_Name")
            OnB_NameChanged()
        End Set
    End Property

    Private _B_Name As Global.System.String
    Private Partial Sub OnB_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnB_NameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property B_Address() As Global.System.String
        Get
            Return _B_Address
        End Get
        Set
            OnB_AddressChanging(value)
            ReportPropertyChanging("B_Address")
            _B_Address = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("B_Address")
            OnB_AddressChanged()
        End Set
    End Property

    Private _B_Address As Global.System.String
    Private Partial Sub OnB_AddressChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnB_AddressChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property B_Landmark() As Global.System.String
        Get
            Return _B_Landmark
        End Get
        Set
            OnB_LandmarkChanging(value)
            ReportPropertyChanging("B_Landmark")
            _B_Landmark = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("B_Landmark")
            OnB_LandmarkChanged()
        End Set
    End Property

    Private _B_Landmark As Global.System.String
    Private Partial Sub OnB_LandmarkChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnB_LandmarkChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property B_city() As Global.System.String
        Get
            Return _B_city
        End Get
        Set
            OnB_cityChanging(value)
            ReportPropertyChanging("B_city")
            _B_city = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("B_city")
            OnB_cityChanged()
        End Set
    End Property

    Private _B_city As Global.System.String
    Private Partial Sub OnB_cityChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnB_cityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property B_state() As Global.System.String
        Get
            Return _B_state
        End Get
        Set
            OnB_stateChanging(value)
            ReportPropertyChanging("B_state")
            _B_state = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("B_state")
            OnB_stateChanged()
        End Set
    End Property

    Private _B_state As Global.System.String
    Private Partial Sub OnB_stateChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnB_stateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property B_zipcode() As Global.System.String
        Get
            Return _B_zipcode
        End Get
        Set
            OnB_zipcodeChanging(value)
            ReportPropertyChanging("B_zipcode")
            _B_zipcode = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("B_zipcode")
            OnB_zipcodeChanged()
        End Set
    End Property

    Private _B_zipcode As Global.System.String
    Private Partial Sub OnB_zipcodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnB_zipcodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property S_Name() As Global.System.String
        Get
            Return _S_Name
        End Get
        Set
            OnS_NameChanging(value)
            ReportPropertyChanging("S_Name")
            _S_Name = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("S_Name")
            OnS_NameChanged()
        End Set
    End Property

    Private _S_Name As Global.System.String
    Private Partial Sub OnS_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnS_NameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property S_address() As Global.System.String
        Get
            Return _S_address
        End Get
        Set
            OnS_addressChanging(value)
            ReportPropertyChanging("S_address")
            _S_address = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("S_address")
            OnS_addressChanged()
        End Set
    End Property

    Private _S_address As Global.System.String
    Private Partial Sub OnS_addressChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnS_addressChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property S_landmark() As Global.System.String
        Get
            Return _S_landmark
        End Get
        Set
            OnS_landmarkChanging(value)
            ReportPropertyChanging("S_landmark")
            _S_landmark = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("S_landmark")
            OnS_landmarkChanged()
        End Set
    End Property

    Private _S_landmark As Global.System.String
    Private Partial Sub OnS_landmarkChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnS_landmarkChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property S_city() As Global.System.String
        Get
            Return _S_city
        End Get
        Set
            OnS_cityChanging(value)
            ReportPropertyChanging("S_city")
            _S_city = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("S_city")
            OnS_cityChanged()
        End Set
    End Property

    Private _S_city As Global.System.String
    Private Partial Sub OnS_cityChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnS_cityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property S_state() As Global.System.String
        Get
            Return _S_state
        End Get
        Set
            OnS_stateChanging(value)
            ReportPropertyChanging("S_state")
            _S_state = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("S_state")
            OnS_stateChanged()
        End Set
    End Property

    Private _S_state As Global.System.String
    Private Partial Sub OnS_stateChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnS_stateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property S_zipcode() As Global.System.String
        Get
            Return _S_zipcode
        End Get
        Set
            OnS_zipcodeChanging(value)
            ReportPropertyChanging("S_zipcode")
            _S_zipcode = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("S_zipcode")
            OnS_zipcodeChanged()
        End Set
    End Property

    Private _S_zipcode As Global.System.String
    Private Partial Sub OnS_zipcodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnS_zipcodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CustomerNo() As Global.System.String
        Get
            Return _CustomerNo
        End Get
        Set
            If (_CustomerNo <> Value) Then
                OnCustomerNoChanging(value)
                ReportPropertyChanging("CustomerNo")
                _CustomerNo = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("CustomerNo")
                OnCustomerNoChanged()
            End If
        End Set
    End Property

    Private _CustomerNo As Global.System.String
    Private Partial Sub OnCustomerNoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCustomerNoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Phone() As Global.System.String
        Get
            Return _Phone
        End Get
        Set
            OnPhoneChanging(value)
            ReportPropertyChanging("Phone")
            _Phone = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Phone")
            OnPhoneChanged()
        End Set
    End Property

    Private _Phone As Global.System.String
    Private Partial Sub OnPhoneChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPhoneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Email() As Global.System.String
        Get
            Return _Email
        End Get
        Set
            OnEmailChanging(value)
            ReportPropertyChanging("Email")
            _Email = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Email")
            OnEmailChanged()
        End Set
    End Property

    Private _Email As Global.System.String
    Private Partial Sub OnEmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEmailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MobileNo() As Global.System.String
        Get
            Return _MobileNo
        End Get
        Set
            OnMobileNoChanging(value)
            ReportPropertyChanging("MobileNo")
            _MobileNo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MobileNo")
            OnMobileNoChanged()
        End Set
    End Property

    Private _MobileNo As Global.System.String
    Private Partial Sub OnMobileNoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMobileNoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FaxNo() As Global.System.String
        Get
            Return _FaxNo
        End Get
        Set
            OnFaxNoChanging(value)
            ReportPropertyChanging("FaxNo")
            _FaxNo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("FaxNo")
            OnFaxNoChanged()
        End Set
    End Property

    Private _FaxNo As Global.System.String
    Private Partial Sub OnFaxNoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFaxNoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Notes() As Global.System.String
        Get
            Return _Notes
        End Get
        Set
            OnNotesChanging(value)
            ReportPropertyChanging("Notes")
            _Notes = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Notes")
            OnNotesChanged()
        End Set
    End Property

    Private _Notes As Global.System.String
    Private Partial Sub OnNotesChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNotesChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SI_DBModel", "FK_BillInfo_Customer", "BillInfo")>
     Public Property BillInfoes() As EntityCollection(Of BillInfo)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of BillInfo)("SI_DBModel.FK_BillInfo_Customer", "BillInfo")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of BillInfo)("SI_DBModel.FK_BillInfo_Customer", "BillInfo", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SI_DBModel", "FK_OrderInfo_Customer", "OrderInfo")>
     Public Property OrderInfoes() As EntityCollection(Of OrderInfo)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of OrderInfo)("SI_DBModel.FK_OrderInfo_Customer", "OrderInfo")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of OrderInfo)("SI_DBModel.FK_OrderInfo_Customer", "OrderInfo", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SI_DBModel", Name:="InventoryCategory")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class InventoryCategory
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new InventoryCategory object.
    ''' </summary>
    ''' <param name="categoryID">Initial value of the CategoryID property.</param>
    Public Shared Function CreateInventoryCategory(categoryID As Global.System.String) As InventoryCategory
        Dim inventoryCategory as InventoryCategory = New InventoryCategory
        inventoryCategory.CategoryID = categoryID
        Return inventoryCategory
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CategoryID() As Global.System.String
        Get
            Return _CategoryID
        End Get
        Set
            If (_CategoryID <> Value) Then
                OnCategoryIDChanging(value)
                ReportPropertyChanging("CategoryID")
                _CategoryID = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("CategoryID")
                OnCategoryIDChanged()
            End If
        End Set
    End Property

    Private _CategoryID As Global.System.String
    Private Partial Sub OnCategoryIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCategoryIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CategoryName() As Global.System.String
        Get
            Return _CategoryName
        End Get
        Set
            OnCategoryNameChanging(value)
            ReportPropertyChanging("CategoryName")
            _CategoryName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CategoryName")
            OnCategoryNameChanged()
        End Set
    End Property

    Private _CategoryName As Global.System.String
    Private Partial Sub OnCategoryNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCategoryNameChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SI_DBModel", Name:="OrderInfo")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class OrderInfo
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new OrderInfo object.
    ''' </summary>
    ''' <param name="orderNo">Initial value of the OrderNo property.</param>
    Public Shared Function CreateOrderInfo(orderNo As Global.System.String) As OrderInfo
        Dim orderInfo as OrderInfo = New OrderInfo
        orderInfo.OrderNo = orderNo
        Return orderInfo
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property OrderNo() As Global.System.String
        Get
            Return _OrderNo
        End Get
        Set
            If (_OrderNo <> Value) Then
                OnOrderNoChanging(value)
                ReportPropertyChanging("OrderNo")
                _OrderNo = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("OrderNo")
                OnOrderNoChanged()
            End If
        End Set
    End Property

    Private _OrderNo As Global.System.String
    Private Partial Sub OnOrderNoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnOrderNoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property OrderDate() As Global.System.String
        Get
            Return _OrderDate
        End Get
        Set
            OnOrderDateChanging(value)
            ReportPropertyChanging("OrderDate")
            _OrderDate = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("OrderDate")
            OnOrderDateChanged()
        End Set
    End Property

    Private _OrderDate As Global.System.String
    Private Partial Sub OnOrderDateChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnOrderDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property OrderStatus() As Global.System.String
        Get
            Return _OrderStatus
        End Get
        Set
            OnOrderStatusChanging(value)
            ReportPropertyChanging("OrderStatus")
            _OrderStatus = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("OrderStatus")
            OnOrderStatusChanged()
        End Set
    End Property

    Private _OrderStatus As Global.System.String
    Private Partial Sub OnOrderStatusChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnOrderStatusChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CustomerNo() As Global.System.String
        Get
            Return _CustomerNo
        End Get
        Set
            OnCustomerNoChanging(value)
            ReportPropertyChanging("CustomerNo")
            _CustomerNo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CustomerNo")
            OnCustomerNoChanged()
        End Set
    End Property

    Private _CustomerNo As Global.System.String
    Private Partial Sub OnCustomerNoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCustomerNoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CustomerName() As Global.System.String
        Get
            Return _CustomerName
        End Get
        Set
            OnCustomerNameChanging(value)
            ReportPropertyChanging("CustomerName")
            _CustomerName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CustomerName")
            OnCustomerNameChanged()
        End Set
    End Property

    Private _CustomerName As Global.System.String
    Private Partial Sub OnCustomerNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCustomerNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SubTotal() As Nullable(Of Global.System.Int32)
        Get
            Return _SubTotal
        End Get
        Set
            OnSubTotalChanging(value)
            ReportPropertyChanging("SubTotal")
            _SubTotal = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SubTotal")
            OnSubTotalChanged()
        End Set
    End Property

    Private _SubTotal As Nullable(Of Global.System.Int32)
    Private Partial Sub OnSubTotalChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnSubTotalChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TaxPercentage() As Nullable(Of Global.System.Double)
        Get
            Return _TaxPercentage
        End Get
        Set
            OnTaxPercentageChanging(value)
            ReportPropertyChanging("TaxPercentage")
            _TaxPercentage = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TaxPercentage")
            OnTaxPercentageChanged()
        End Set
    End Property

    Private _TaxPercentage As Nullable(Of Global.System.Double)
    Private Partial Sub OnTaxPercentageChanging(value As Nullable(Of Global.System.Double))
    End Sub

    Private Partial Sub OnTaxPercentageChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TaxAmount() As Nullable(Of Global.System.Int32)
        Get
            Return _TaxAmount
        End Get
        Set
            OnTaxAmountChanging(value)
            ReportPropertyChanging("TaxAmount")
            _TaxAmount = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TaxAmount")
            OnTaxAmountChanged()
        End Set
    End Property

    Private _TaxAmount As Nullable(Of Global.System.Int32)
    Private Partial Sub OnTaxAmountChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnTaxAmountChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TotalAmount() As Nullable(Of Global.System.Int32)
        Get
            Return _TotalAmount
        End Get
        Set
            OnTotalAmountChanging(value)
            ReportPropertyChanging("TotalAmount")
            _TotalAmount = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TotalAmount")
            OnTotalAmountChanged()
        End Set
    End Property

    Private _TotalAmount As Nullable(Of Global.System.Int32)
    Private Partial Sub OnTotalAmountChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnTotalAmountChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SI_DBModel", "FK_OrderInfo_Customer", "Customer")>
    Public Property Customer() As Customer
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("SI_DBModel.FK_OrderInfo_Customer", "Customer").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("SI_DBModel.FK_OrderInfo_Customer", "Customer").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CustomerReference() As EntityReference(Of Customer)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("SI_DBModel.FK_OrderInfo_Customer", "Customer")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Customer)("SI_DBModel.FK_OrderInfo_Customer", "Customer", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SI_DBModel", Name:="Product")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Product
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Product object.
    ''' </summary>
    ''' <param name="productCode">Initial value of the ProductCode property.</param>
    Public Shared Function CreateProduct(productCode As Global.System.String) As Product
        Dim product as Product = New Product
        product.ProductCode = productCode
        Return product
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ProductCode() As Global.System.String
        Get
            Return _ProductCode
        End Get
        Set
            If (_ProductCode <> Value) Then
                OnProductCodeChanging(value)
                ReportPropertyChanging("ProductCode")
                _ProductCode = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("ProductCode")
                OnProductCodeChanged()
            End If
        End Set
    End Property

    Private _ProductCode As Global.System.String
    Private Partial Sub OnProductCodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnProductCodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ProductName() As Global.System.String
        Get
            Return _ProductName
        End Get
        Set
            OnProductNameChanging(value)
            ReportPropertyChanging("ProductName")
            _ProductName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ProductName")
            OnProductNameChanged()
        End Set
    End Property

    Private _ProductName As Global.System.String
    Private Partial Sub OnProductNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnProductNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Category() As Global.System.String
        Get
            Return _Category
        End Get
        Set
            OnCategoryChanging(value)
            ReportPropertyChanging("Category")
            _Category = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Category")
            OnCategoryChanged()
        End Set
    End Property

    Private _Category As Global.System.String
    Private Partial Sub OnCategoryChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCategoryChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Weight() As Global.System.String
        Get
            Return _Weight
        End Get
        Set
            OnWeightChanging(value)
            ReportPropertyChanging("Weight")
            _Weight = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Weight")
            OnWeightChanged()
        End Set
    End Property

    Private _Weight As Global.System.String
    Private Partial Sub OnWeightChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnWeightChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Price() As Nullable(Of Global.System.Double)
        Get
            Return _Price
        End Get
        Set
            OnPriceChanging(value)
            ReportPropertyChanging("Price")
            _Price = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Price")
            OnPriceChanged()
        End Set
    End Property

    Private _Price As Nullable(Of Global.System.Double)
    Private Partial Sub OnPriceChanging(value As Nullable(Of Global.System.Double))
    End Sub

    Private Partial Sub OnPriceChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SI_DBModel", "FK_Stock_Product", "Stock")>
     Public Property Stocks() As EntityCollection(Of Stock)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Stock)("SI_DBModel.FK_Stock_Product", "Stock")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Stock)("SI_DBModel.FK_Stock_Product", "Stock", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SI_DBModel", Name:="Registration")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Registration
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Registration object.
    ''' </summary>
    ''' <param name="username">Initial value of the Username property.</param>
    Public Shared Function CreateRegistration(username As Global.System.String) As Registration
        Dim registration as Registration = New Registration
        registration.Username = username
        Return registration
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Username() As Global.System.String
        Get
            Return _Username
        End Get
        Set
            If (_Username <> Value) Then
                OnUsernameChanging(value)
                ReportPropertyChanging("Username")
                _Username = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Username")
                OnUsernameChanged()
            End If
        End Set
    End Property

    Private _Username As Global.System.String
    Private Partial Sub OnUsernameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUsernameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Password() As Global.System.String
        Get
            Return _Password
        End Get
        Set
            OnPasswordChanging(value)
            ReportPropertyChanging("Password")
            _Password = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Password")
            OnPasswordChanged()
        End Set
    End Property

    Private _Password As Global.System.String
    Private Partial Sub OnPasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPasswordChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ContactNo() As Global.System.String
        Get
            Return _ContactNo
        End Get
        Set
            OnContactNoChanging(value)
            ReportPropertyChanging("ContactNo")
            _ContactNo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ContactNo")
            OnContactNoChanged()
        End Set
    End Property

    Private _ContactNo As Global.System.String
    Private Partial Sub OnContactNoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnContactNoChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SI_DBModel", Name:="Stock")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Stock
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Stock object.
    ''' </summary>
    ''' <param name="stockID">Initial value of the StockID property.</param>
    Public Shared Function CreateStock(stockID As Global.System.String) As Stock
        Dim stock as Stock = New Stock
        stock.StockID = stockID
        Return stock
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property StockID() As Global.System.String
        Get
            Return _StockID
        End Get
        Set
            If (_StockID <> Value) Then
                OnStockIDChanging(value)
                ReportPropertyChanging("StockID")
                _StockID = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("StockID")
                OnStockIDChanged()
            End If
        End Set
    End Property

    Private _StockID As Global.System.String
    Private Partial Sub OnStockIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStockIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ProductCode() As Global.System.String
        Get
            Return _ProductCode
        End Get
        Set
            OnProductCodeChanging(value)
            ReportPropertyChanging("ProductCode")
            _ProductCode = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ProductCode")
            OnProductCodeChanged()
        End Set
    End Property

    Private _ProductCode As Global.System.String
    Private Partial Sub OnProductCodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnProductCodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ProductName() As Global.System.String
        Get
            Return _ProductName
        End Get
        Set
            OnProductNameChanging(value)
            ReportPropertyChanging("ProductName")
            _ProductName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ProductName")
            OnProductNameChanged()
        End Set
    End Property

    Private _ProductName As Global.System.String
    Private Partial Sub OnProductNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnProductNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Category() As Global.System.String
        Get
            Return _Category
        End Get
        Set
            OnCategoryChanging(value)
            ReportPropertyChanging("Category")
            _Category = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Category")
            OnCategoryChanged()
        End Set
    End Property

    Private _Category As Global.System.String
    Private Partial Sub OnCategoryChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCategoryChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Weight() As Global.System.String
        Get
            Return _Weight
        End Get
        Set
            OnWeightChanging(value)
            ReportPropertyChanging("Weight")
            _Weight = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Weight")
            OnWeightChanged()
        End Set
    End Property

    Private _Weight As Global.System.String
    Private Partial Sub OnWeightChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnWeightChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Stockdate() As Global.System.String
        Get
            Return _Stockdate
        End Get
        Set
            OnStockdateChanging(value)
            ReportPropertyChanging("Stockdate")
            _Stockdate = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Stockdate")
            OnStockdateChanged()
        End Set
    End Property

    Private _Stockdate As Global.System.String
    Private Partial Sub OnStockdateChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStockdateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Cartons() As Nullable(Of Global.System.Int32)
        Get
            Return _Cartons
        End Get
        Set
            OnCartonsChanging(value)
            ReportPropertyChanging("Cartons")
            _Cartons = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Cartons")
            OnCartonsChanged()
        End Set
    End Property

    Private _Cartons As Nullable(Of Global.System.Int32)
    Private Partial Sub OnCartonsChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnCartonsChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Packets() As Nullable(Of Global.System.Int32)
        Get
            Return _Packets
        End Get
        Set
            OnPacketsChanging(value)
            ReportPropertyChanging("Packets")
            _Packets = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Packets")
            OnPacketsChanged()
        End Set
    End Property

    Private _Packets As Nullable(Of Global.System.Int32)
    Private Partial Sub OnPacketsChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnPacketsChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TotalPackets() As Nullable(Of Global.System.Int32)
        Get
            Return _TotalPackets
        End Get
        Set
            OnTotalPacketsChanging(value)
            ReportPropertyChanging("TotalPackets")
            _TotalPackets = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TotalPackets")
            OnTotalPacketsChanged()
        End Set
    End Property

    Private _TotalPackets As Nullable(Of Global.System.Int32)
    Private Partial Sub OnTotalPacketsChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnTotalPacketsChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SI_DBModel", "FK_Stock_Product", "Product")>
    Public Property Product() As Product
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("SI_DBModel.FK_Stock_Product", "Product").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("SI_DBModel.FK_Stock_Product", "Product").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ProductReference() As EntityReference(Of Product)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("SI_DBModel.FK_Stock_Product", "Product")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Product)("SI_DBModel.FK_Stock_Product", "Product", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SI_DBModel", Name:="sysdiagram")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class sysdiagram
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new sysdiagram object.
    ''' </summary>
    ''' <param name="name">Initial value of the name property.</param>
    ''' <param name="principal_id">Initial value of the principal_id property.</param>
    ''' <param name="diagram_id">Initial value of the diagram_id property.</param>
    Public Shared Function Createsysdiagram(name As Global.System.String, principal_id As Global.System.Int32, diagram_id As Global.System.Int32) As sysdiagram
        Dim sysdiagram as sysdiagram = New sysdiagram
        sysdiagram.name = name
        sysdiagram.principal_id = principal_id
        sysdiagram.diagram_id = diagram_id
        Return sysdiagram
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property principal_id() As Global.System.Int32
        Get
            Return _principal_id
        End Get
        Set
            Onprincipal_idChanging(value)
            ReportPropertyChanging("principal_id")
            _principal_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("principal_id")
            Onprincipal_idChanged()
        End Set
    End Property

    Private _principal_id As Global.System.Int32
    Private Partial Sub Onprincipal_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onprincipal_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property diagram_id() As Global.System.Int32
        Get
            Return _diagram_id
        End Get
        Set
            If (_diagram_id <> Value) Then
                Ondiagram_idChanging(value)
                ReportPropertyChanging("diagram_id")
                _diagram_id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("diagram_id")
                Ondiagram_idChanged()
            End If
        End Set
    End Property

    Private _diagram_id As Global.System.Int32
    Private Partial Sub Ondiagram_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Ondiagram_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property version() As Nullable(Of Global.System.Int32)
        Get
            Return _version
        End Get
        Set
            OnversionChanging(value)
            ReportPropertyChanging("version")
            _version = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("version")
            OnversionChanged()
        End Set
    End Property

    Private _version As Nullable(Of Global.System.Int32)
    Private Partial Sub OnversionChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnversionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property definition() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_definition)
        End Get
        Set
            OndefinitionChanging(value)
            ReportPropertyChanging("definition")
            _definition = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("definition")
            OndefinitionChanged()
        End Set
    End Property

    Private _definition As Global.System.Byte()
    Private Partial Sub OndefinitionChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OndefinitionChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SI_DBModel", Name:="User")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class User
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new User object.
    ''' </summary>
    ''' <param name="userName">Initial value of the UserName property.</param>
    Public Shared Function CreateUser(userName As Global.System.String) As User
        Dim user as User = New User
        user.UserName = userName
        Return user
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property UserName() As Global.System.String
        Get
            Return _UserName
        End Get
        Set
            If (_UserName <> Value) Then
                OnUserNameChanging(value)
                ReportPropertyChanging("UserName")
                _UserName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("UserName")
                OnUserNameChanged()
            End If
        End Set
    End Property

    Private _UserName As Global.System.String
    Private Partial Sub OnUserNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUserNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Password() As Global.System.String
        Get
            Return _Password
        End Get
        Set
            OnPasswordChanging(value)
            ReportPropertyChanging("Password")
            _Password = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Password")
            OnPasswordChanged()
        End Set
    End Property

    Private _Password As Global.System.String
    Private Partial Sub OnPasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPasswordChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SI_DBModel", Name:="Vendor")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Vendor
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Vendor object.
    ''' </summary>
    ''' <param name="vendorID">Initial value of the VendorID property.</param>
    Public Shared Function CreateVendor(vendorID As Global.System.String) As Vendor
        Dim vendor as Vendor = New Vendor
        vendor.VendorID = vendorID
        Return vendor
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property VendorID() As Global.System.String
        Get
            Return _VendorID
        End Get
        Set
            If (_VendorID <> Value) Then
                OnVendorIDChanging(value)
                ReportPropertyChanging("VendorID")
                _VendorID = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("VendorID")
                OnVendorIDChanged()
            End If
        End Set
    End Property

    Private _VendorID As Global.System.String
    Private Partial Sub OnVendorIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnVendorIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Address() As Global.System.String
        Get
            Return _Address
        End Get
        Set
            OnAddressChanging(value)
            ReportPropertyChanging("Address")
            _Address = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Address")
            OnAddressChanged()
        End Set
    End Property

    Private _Address As Global.System.String
    Private Partial Sub OnAddressChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAddressChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Landmark() As Global.System.String
        Get
            Return _Landmark
        End Get
        Set
            OnLandmarkChanging(value)
            ReportPropertyChanging("Landmark")
            _Landmark = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Landmark")
            OnLandmarkChanged()
        End Set
    End Property

    Private _Landmark As Global.System.String
    Private Partial Sub OnLandmarkChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLandmarkChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property City() As Global.System.String
        Get
            Return _City
        End Get
        Set
            OnCityChanging(value)
            ReportPropertyChanging("City")
            _City = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("City")
            OnCityChanged()
        End Set
    End Property

    Private _City As Global.System.String
    Private Partial Sub OnCityChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property State() As Global.System.String
        Get
            Return _State
        End Get
        Set
            OnStateChanging(value)
            ReportPropertyChanging("State")
            _State = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("State")
            OnStateChanged()
        End Set
    End Property

    Private _State As Global.System.String
    Private Partial Sub OnStateChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ZipCode() As Global.System.String
        Get
            Return _ZipCode
        End Get
        Set
            OnZipCodeChanging(value)
            ReportPropertyChanging("ZipCode")
            _ZipCode = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ZipCode")
            OnZipCodeChanged()
        End Set
    End Property

    Private _ZipCode As Global.System.String
    Private Partial Sub OnZipCodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnZipCodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Phone() As Global.System.String
        Get
            Return _Phone
        End Get
        Set
            OnPhoneChanging(value)
            ReportPropertyChanging("Phone")
            _Phone = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Phone")
            OnPhoneChanged()
        End Set
    End Property

    Private _Phone As Global.System.String
    Private Partial Sub OnPhoneChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPhoneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Email() As Global.System.String
        Get
            Return _Email
        End Get
        Set
            OnEmailChanging(value)
            ReportPropertyChanging("Email")
            _Email = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Email")
            OnEmailChanged()
        End Set
    End Property

    Private _Email As Global.System.String
    Private Partial Sub OnEmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEmailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MobileNo() As Global.System.String
        Get
            Return _MobileNo
        End Get
        Set
            OnMobileNoChanging(value)
            ReportPropertyChanging("MobileNo")
            _MobileNo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MobileNo")
            OnMobileNoChanged()
        End Set
    End Property

    Private _MobileNo As Global.System.String
    Private Partial Sub OnMobileNoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMobileNoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FaxNo() As Global.System.String
        Get
            Return _FaxNo
        End Get
        Set
            OnFaxNoChanging(value)
            ReportPropertyChanging("FaxNo")
            _FaxNo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("FaxNo")
            OnFaxNoChanged()
        End Set
    End Property

    Private _FaxNo As Global.System.String
    Private Partial Sub OnFaxNoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFaxNoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Notes() As Global.System.String
        Get
            Return _Notes
        End Get
        Set
            OnNotesChanging(value)
            ReportPropertyChanging("Notes")
            _Notes = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Notes")
            OnNotesChanged()
        End Set
    End Property

    Private _Notes As Global.System.String
    Private Partial Sub OnNotesChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNotesChanged()
    End Sub

    #End Region

End Class

#End Region


